version: "3.8"

services:
    # nestjs-app:
    #     image: node:22-alpine3.18
    #     ports:
    #         - "${APP_PORT}:${APP_PORT}"
    #     depends_on:
    #         - postgres
    #     environment:
    #         # App
    #         APP_NAME: ${APP_NAME}
    #         APP_VERSION: ${APP_VERSION}
    #         APP_ENV: ${APP_ENV}
    #         APP_PORT: ${APP_PORT}
    #         # Database
    #         DATABASE_PORT: ${DATABASE_PORT}
    #         DATABASE_NAME: ${DATABASE_NAME}
    #         DATABASE_URL: ${DATABASE_URL}

    postgres:
        image: postgres:latest
        ports:
            - "${DATABASE_PORT}:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./scripts/create-postgres-db.sql:/docker-entrypoint-initdb.d/create-postgres-db.sql

volumes:
    postgres_data:
